server:
  port: 7075
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: arsham
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /faraway
      enabled: true


